name: Custom Model build

on:
  push:
    branches: [ "main1" ]
  pull_request:
    branches: [ "main1" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.repository }}
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
          role-to-assume: arn:aws:iam::270932919550:role/git-actions-iam 
          aws-region: us-east-1
    
    - name: setup python
      uses: actions/setup-python@v4
      with:
          python-version: '3.10' # install the python version needed
    
    - name: Install dependencies
      run: pip install boto3

    - name: Download python code
      run: |
          aws s3 cp s3://siri-python-code/dynamodb-git-update.py dynamodb-git-update.py
          aws s3 cp s3://siri-python-code/download-s3.py download-s3.py
   
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
   
    - name: download model
      run: |
            python download-s3.py 

    - name: Create ECR registry (if needed)
      id: create-ecr
      run: |
           aws ecr create-repository --repository-name ${{ github.event.repository.name }} || true
            
    #- name: Build the Docker image
     # run: |
      
      #    docker build -t ${{ github.event.repository.name }} .
       #   docker tag ${{ github.event.repository.name }}:latest ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ env.new_version }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: buuld_docker
      uses: docker/build-push-action@v2
      with:
        push: true
        image: ${{ github.workspace }} 
        tags:  ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ env.new_version }}
      
    #- name: Docker Push
     # run: |
      #    set -e
       #   docker push ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ env.new_version }}
    - name: Update Dynamo
      run: |
            python dynamodb-git-update.py ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}
